'use client';
import { FirebaseOptions } from 'firebase/app';

// This file is automatically generated. You may edit it locally but it will be replaced by the values found in the backend.
export const firebaseConfig: FirebaseOptions = {
  "projectId": "studio-5218899653-d333b",
  "appId": "1:534626091746:web:6e3e901a6138a1665754bb",
  "apiKey": "AIzaSyDG0UPVLgFfsZWvCqByvdXc3_daDbpKLzo",
  "authDomain": "studio-5218899653-d333b.firebaseapp.com",
  "storageBucket": "studio-5218899653-d333b.appspot.com",
  "messagingSenderId": "534626091746",
};
