'use client';
import { FirebaseOptions } from 'firebase/app';

// This file is automatically generated. You may edit it locally but it will be replaced by the values found in the backend.
export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyDG0UPVLgFfsZWvCqByvdXc3_daDbpKLzo",
  appId: "1:534626091746:web:6e3e901a6138a1665754bb",
  authDomain: "studio-5218899653-d333b.firebaseapp.com",
  measurementId: "",
  messagingSenderId: "534626091746",
  projectId: "studio-5218899653-d333b"
}
